# Uncomment the next line to define a global platform for your project
 platform :ios, ‘9.0’

target 'Demo8-homePage_newsToday' do

  use_frameworks!
pod 'Moya/RxSwift'
pod 'SwiftyJSON'
pod 'SnapKit'
pod 'SVProgressHUD'                 # 提示功能 https://github.com/SVProgressHUD/SVProgressHUD
pod 'MJRefresh'  


        








end
